version: '3.3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.umich
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST:-qualtrics-lti.docker}
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root
      LOG_CHANNEL: errorlog
      LOG_LEVEL: debug
      SESSION_DRIVER: file
    env_file:
      - .env
    links:
      - "mysql:mysql"
    ports:
      - "8080:80"
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
