FROM ghcr.io/longhornopen/qualtrics-lti:20230215

# Update lax to none in the session config
RUN sed -i s/lax/none/ /var/www/html/config/session.php

# https://documentation.its.umich.edu/node/2118
RUN useradd -g root -m -s /bin/bash -l -o -u 1000940000 www-root
